// GENERATED from web/src/app/decks/review/battle/_lib/fixtures/sprites.fixture.json
// (itself exported from sprites.ts / monsters.ts). Do not hand-edit:
// test/sprites_test.dart fails if this drifts from the fixture.

/// Clip lengths (sprites.ts): one-shots run faster than the looping idle/walk.
const oneShotMs = 500;
const loopMs = 900;

/// Frames per clip, per character. Every character has `idle`.
const spriteFrames = <String, Map<String, int>>{
  'archer': {'idle': 6, 'walk': 8, 'attack01': 9, 'attack02': 12, 'hurt': 4, 'death': 4},
  'armored-axeman': {'idle': 6, 'walk': 8, 'attack01': 9, 'attack02': 9, 'attack03': 12, 'hurt': 4, 'death': 4},
  'armored-orc': {'idle': 6, 'walk': 8, 'attack01': 7, 'attack02': 8, 'attack03': 9, 'hurt': 4, 'death': 4, 'block': 4},
  'armored-skeleton': {'idle': 6, 'walk': 8, 'attack01': 8, 'attack02': 9, 'hurt': 4, 'death': 4},
  'bat': {'idle': 6, 'attack01': 6, 'attack02': 7, 'hurt': 4, 'death': 4},
  'black-knight-a': {'idle': 6, 'walk': 8, 'attack01': 16, 'attack02': 15, 'attack03': 15, 'hurt': 4, 'death': 4},
  'black-knight-b': {'idle': 6, 'walk': 8, 'attack01': 7, 'attack02': 8, 'attack03': 9, 'hurt': 4, 'death': 4, 'block': 4},
  'black-knight-c': {'idle': 6, 'walk': 8, 'attack01': 8, 'attack02': 9, 'attack03': 13, 'hurt': 4, 'death': 10},
  'blood-monster-a': {'idle': 6, 'walk': 8, 'attack01': 8, 'attack02': 8, 'hurt': 4, 'death': 4},
  'blood-monster-b': {'idle': 6, 'attack01': 8, 'attack02': 9, 'hurt': 4, 'death': 6},
  'demon-a': {'idle': 6, 'walk': 8, 'attack01': 7, 'attack02': 7, 'hurt': 4, 'death': 4},
  'demon-b': {'idle': 6, 'walk': 8, 'attack01': 9, 'attack02': 6, 'hurt': 4, 'death': 4},
  'demon-c': {'idle': 6, 'walk': 6, 'attack01': 6, 'attack02': 6, 'hurt': 4, 'death': 4},
  'demon-d': {'idle': 6, 'walk': 8, 'attack01': 11, 'attack02': 18, 'attack03': 12, 'hurt': 4, 'death': 4},
  'demon-e': {'idle': 6, 'walk': 8, 'attack01': 8, 'attack02': 13, 'attack03': 8, 'hurt': 4, 'death': 4},
  'demoness-a': {'idle': 6, 'walk': 8, 'attack01': 9, 'attack02': 15, 'attack03': 16, 'hurt': 4, 'death': 4},
  'demoness-b': {'idle': 6, 'walk': 6, 'attack01': 8, 'attack02': 8, 'hurt': 4, 'death': 4},
  'elite-orc': {'idle': 6, 'walk': 8, 'attack01': 7, 'attack02': 11, 'attack03': 9, 'hurt': 4, 'death': 4},
  'eyeball-monster': {'idle': 6, 'walk': 6, 'attack01': 8, 'attack02': 8, 'attack03': 6, 'hurt': 4, 'death': 4},
  'flame-golem': {'idle': 6, 'walk': 12, 'attack01': 9, 'attack02': 9, 'attack03': 9, 'hurt': 4, 'death': 6},
  'ghostfire': {'idle': 6, 'attack01': 6, 'attack02': 7, 'hurt': 4, 'death': 6},
  'greatsword-skeleton': {'idle': 6, 'walk': 9, 'attack01': 9, 'attack02': 12, 'attack03': 8, 'hurt': 4, 'death': 4},
  'hellbat': {'idle': 6, 'attack01': 6, 'attack02': 7, 'hurt': 4, 'death': 4},
  'hellhound': {'idle': 6, 'walk': 8, 'attack01': 8, 'attack02': 8, 'hurt': 4, 'death': 4},
  'knight': {'idle': 6, 'walk': 8, 'attack01': 7, 'attack02': 10, 'attack03': 11, 'hurt': 4, 'death': 4, 'block': 4},
  'knight-templar': {'idle': 6, 'walk': 8, 'attack01': 7, 'attack02': 8, 'attack03': 11, 'hurt': 4, 'death': 4, 'block': 4},
  'lancer': {'idle': 6, 'walk': 8, 'attack01': 6, 'attack02': 9, 'attack03': 8, 'hurt': 4, 'death': 4},
  'lava-slime': {'idle': 6, 'walk': 6, 'attack01': 6, 'attack02': 9, 'hurt': 4, 'death': 4},
  'minotaur': {'idle': 6, 'walk': 8, 'attack01': 8, 'attack02': 7, 'attack03': 7, 'hurt': 4, 'death': 4},
  'necromancer': {'idle': 6, 'walk': 6, 'attack01': 9, 'attack02': 10, 'hurt': 4, 'death': 9},
  'orc': {'idle': 6, 'walk': 8, 'attack01': 6, 'attack02': 6, 'hurt': 4, 'death': 4},
  'orc-rider': {'idle': 6, 'walk': 8, 'attack01': 8, 'attack02': 9, 'attack03': 11, 'hurt': 4, 'death': 4, 'block': 4},
  'priest': {'idle': 6, 'walk': 8, 'attack01': 9, 'hurt': 4, 'death': 4},
  'skeleton': {'idle': 6, 'walk': 8, 'attack01': 6, 'attack02': 7, 'hurt': 4, 'death': 4, 'block': 4},
  'skeleton-archer': {'idle': 6, 'walk': 8, 'attack01': 9, 'hurt': 4, 'death': 4},
  'slime': {'idle': 6, 'walk': 6, 'attack01': 6, 'attack02': 12, 'hurt': 4, 'death': 4},
  'soldier': {'idle': 6, 'walk': 8, 'attack01': 6, 'attack02': 6, 'attack03': 9, 'hurt': 4, 'death': 4},
  'swordsman': {'idle': 6, 'walk': 8, 'attack01': 7, 'attack02': 15, 'attack03': 12, 'hurt': 5, 'death': 4},
  'warlock': {'idle': 6, 'walk': 8, 'attack01': 7, 'attack02': 6, 'hurt': 4, 'death': 11},
  'werebear': {'idle': 6, 'walk': 8, 'attack01': 9, 'attack02': 13, 'attack03': 9, 'hurt': 4, 'death': 4},
  'werewolf': {'idle': 6, 'walk': 8, 'attack01': 9, 'attack02': 13, 'hurt': 4, 'death': 4},
  'wizard': {'idle': 6, 'walk': 8, 'attack01': 6, 'attack02': 9, 'hurt': 4, 'death': 4},
};

/// Correction (frame px) that centres each character in its 100px frame,
/// measured from its idle clip and applied to every pose (sprites.ts).
const spriteOffsets = <String, ({int x, int y})>{
  'archer': (x: -1, y: 0),
  'armored-axeman': (x: -3, y: 2),
  'armored-orc': (x: -4, y: 2),
  'armored-skeleton': (x: -4, y: 3),
  'bat': (x: 0, y: 2),
  'black-knight-a': (x: -2, y: 6),
  'black-knight-b': (x: 0, y: 2),
  'black-knight-c': (x: -6, y: 6),
  'blood-monster-a': (x: -2, y: -1),
  'blood-monster-b': (x: -3, y: 3),
  'demon-a': (x: -3, y: 1),
  'demon-b': (x: -2, y: 0),
  'demon-c': (x: -4, y: 4),
  'demon-d': (x: -6, y: 4),
  'demon-e': (x: -5, y: 2),
  'demoness-a': (x: -5, y: 4),
  'demoness-b': (x: 1, y: 3),
  'elite-orc': (x: -6, y: 4),
  'eyeball-monster': (x: 0, y: -2),
  'flame-golem': (x: -2, y: 6),
  'ghostfire': (x: -2, y: 7),
  'greatsword-skeleton': (x: 6, y: 2),
  'hellbat': (x: 1, y: 4),
  'hellhound': (x: 0, y: 0),
  'knight': (x: -4, y: 1),
  'knight-templar': (x: -6, y: 0),
  'lancer': (x: 0, y: 10),
  'lava-slime': (x: 2, y: -1),
  'minotaur': (x: -6, y: 1),
  'necromancer': (x: 4, y: 5),
  'orc': (x: -4, y: 0),
  'orc-rider': (x: -3, y: 6),
  'priest': (x: -2, y: 2),
  'skeleton': (x: -6, y: 0),
  'skeleton-archer': (x: -2, y: 2),
  'slime': (x: 2, y: 0),
  'soldier': (x: 0, y: 1),
  'swordsman': (x: -4, y: 1),
  'warlock': (x: 0, y: 4),
  'werebear': (x: -2, y: 0),
  'werewolf': (x: -6, y: 0),
  'wizard': (x: -2, y: 1),
};

const playerRoster = <String>[
  'archer',
  'armored-axeman',
  'knight',
  'knight-templar',
  'lancer',
  'priest',
  'soldier',
  'swordsman',
  'wizard',
  'black-knight-a',
  'black-knight-b',
  'black-knight-c',
];

const monsterRoster = <String>[
  'armored-orc',
  'armored-skeleton',
  'bat',
  'black-knight-a',
  'black-knight-b',
  'black-knight-c',
  'blood-monster-a',
  'blood-monster-b',
  'demon-a',
  'demon-b',
  'demon-c',
  'demon-d',
  'demon-e',
  'demoness-a',
  'demoness-b',
  'elite-orc',
  'eyeball-monster',
  'flame-golem',
  'ghostfire',
  'greatsword-skeleton',
  'hellbat',
  'hellhound',
  'lava-slime',
  'minotaur',
  'necromancer',
  'orc',
  'orc-rider',
  'skeleton',
  'skeleton-archer',
  'slime',
  'warlock',
  'werebear',
  'werewolf',
];

const defaultPlayerCharacter = 'knight';
