// Mongolian UI strings (all users are Mongolian).
export const T = {
  folders: "Хавтаснууд",
  allDecks: "Бүх багц",
  noFolder: "Хавтасгүй",
  newFolder: "Шинэ хавтасны нэр",
  newFolderTitle: "Шинэ хавтас нэмэх",
  newSubfolder: "Дотор нь хавтас нэмэх",
  folderMoveFailed: "Хавтсыг зөөж чадсангүй.",
  emptyFolder: "хоосон",
  decks: "Багцууд",
  folderShort: "Хавтас",
  deckShort: "Багц",
  newKindLabel: "Юу нэмэх",
  filterDecks: "Багц шүүх…",
  clearFilter: "Шүүлтүүр цэвэрлэх",
  newDeck: "Шинэ багцын нэр",
  add: "Нэмэх",
  noDecks: "Багц алга",
  loading: "Ачааллаж байна…",
  createDeckToStart: "Эхлэхийн тулд багц үүсгэнэ үү.",
  search: "Үг хайх…",
  searchResults: "Хайлтын үр дүн",
  noResults: "Илэрц олдсонгүй",
  noWords: "Энэ багцад үг алга. Дээр нэмэх эсвэл өргөтгөлөөс хадгална уу.",
  exportApkg: ".apkg татах",
  building: "Бэлдэж байна…",
  exportFailed: "Экспорт амжилтгүй",
  delete: "Устгах",
  term: "Үг (ж: 勉強)",
  reading: "Дуудлага",
  lookingUp: "Хайж байна…",
  meaningEn: "Утга (Англи)",
  mongolian: "Монгол",
  addWord: "Үг нэмэх",
  clickToRename: "Нэр солих бол дарна уу",
  playAudio: "Дуудлага сонсох",
  removeWord: "Үг устгах",
  edit: "Засах",
  editWord: "Үг засах",
  refresh: "Шинэчлэх",
  research: "Jisho-оос дахин хайх",
  translate: "Орчуулах",
  save: "Хадгалах",
  cancel: "Болих",
  gridView: "Картаар харах",
  listView: "Жагсаалтаар харах",
  noFolderOption: "— Хавтасгүй —",
  audioFailed: "Дуу үүсгэж чадсангүй",
  deleteDeckConfirm: (n: string) =>
    `“${n}” багц болон доторх бүх үгийг устгах уу? Буцаах боломжгүй.`,
  deleteFolderConfirm: (n: string) =>
    `“${n}” хавтсыг устгах уу? Доторх багцууд устахгүй, хавтасгүй болно.`,
  duplicateWord: "Давхардсан үг",
  duplicateWordConfirm: (t: string) =>
    `“${t}” энэ багцад аль хэдийн бүртгэгдсэн байна. Дахин нэмэх үү?`,
  addAnyway: "Дахин нэмэх",
  practice: "Давтах",
  practiceAll: "Давтах",
  loadingWords: "Үгсийг ачааллаж байна…",
  noWordsDue: "Одоогоор давтах үг алга. Дараа дахин ирнэ үү!",
  showAnswer: "Хариулт харах",
  again: "Дахин",
  hard: "Хэцүү",
  good: "Сайн",
  easy: "Амархан",
  // Practice session chrome
  spaceHint: "Зай",
  exitSession: "Дуусгах",
  undo: "Буцаах",
  undoTitle: "Сүүлийн хариултыг буцаах",
  progressLabel: (done: number, total: number) => `${done} / ${total}`,
  remainingN: (n: number) => `${n} үг үлдсэн`,
  againSoon: "Одоо дахин",
  intervalMinutes: (n: number) => `${n} мин`,
  intervalDays: (n: number) => `${n} өдөр`,
  intervalMonths: (n: number) => `${n} сар`,
  intervalYears: (n: number) => `${n} жил`,
  reviewAgain: "Дахин давтах",
  sessionStatWords: "Давтсан үг",
  keyboardHint: "Зай — хариулт · 1-4 — үнэлгээ",
  sessionComplete: "Давтаж дууслаа!",
  sessionCompleteDesc: (n: number) => `Та ${n} үг дахин үзлээ.`,
  backToDecks: "Багцууд руу буцах",
  gradeTitle: "Түвшин",
  gradeNew: "Шинэ",
  gradeClearFilter: "Шүүлтүүр арилгах",
  gradeFilterEmpty: "Энэ түвшинд үг алга.",
  dashboardNav: "Хяналтын самбар",
  decksNav: "Багцууд",
  practiceNav: "Давтах",
  homeTab: "Нүүр",
  duelTab: "Тулаан",
  mainNav: "Үндсэн цэс",
  signOut: "Гарах",
  moreActions: "Бусад үйлдэл",
  // Mode chooser (/decks/review)
  chooseModeTitle: "Ямар байдлаар давтах вэ?",
  classicModeTitle: "Энгийн давталт",
  classicModeDesc: "Дөрвөн товчоор өөрөө үнэлж давтана.",
  battleModeTitle: "Мангас агнах",
  battleModeDesc: "Зөв хариултаар дайсныг цохино, буруу хариулбал өөрөө цохиулна.",
  startButton: "Эхлэх",
  // Quiz + battle
  loadingQuiz: "Асуулт бэлдэж байна…",
  noWordsDueBattle: "Одоогоор тулаанд дайх үг алга байна.",
  noWordsDueBattleHint:
    "Бүх үгээ давтсан байна. Сурч буй үгс хэдэн минутын дараа эргэж ирнэ.",
  queueLoadFailed: "Давтах үгсийг ачаалж чадсангүй.",
  freePracticeCta: "Ямар ч үгээр чөлөөтэй тулаанд орох",
  freePracticeBanner:
    "Чөлөөт дасгал — хариултууд давтлагын хуваарь болон цувралд нөлөөлөхгүй.",
  freeModeTitle: "Чөлөөт дасгал",
  freeModeDesc:
    "Хуваариас үл хамааран дурын үгээр тулаанд орно. Хуваарь өөрчлөгдөхгүй.",
  notEnoughWordsBattle:
    "Мангас агнахад хамгийн багадаа 4 үг хэрэгтэй. Эхлээд өргөтгөл эсвэл гараар цөөн үг нэмнэ үү.",
  fightButton: "Тулаанд орох",
  // Practice landing page (/decks/review). The chooser used to say nothing
  // about whether there was anything to practise, so two of its three options
  // were dead ends on a finished day and you only found that out by clicking.
  practiceKicker: "Өнөөдрийн давталт",
  practiceDueHeadline: (n: number) => `${n} үг хүлээж байна`,
  practiceNothingDue: "Өнөөдөр давтах үг алга",
  practiceNothingDueSub:
    "Хуваарийн бүх үгээ давж дууслаа. Хүсвэл доорх чөлөөт дасгалаар үргэлжлүүлээрэй.",
  practiceDueBreakdown: (review: number, fresh: number) =>
    `${review} давталт · ${fresh} шинэ`,
  practiceScopeLabel: "Багц сонгох",
  practiceScopeAll: "Бүх багц",
  practiceStart: "Эхлэх",
  heroPickerTitle: "Баатраа сонго",
  heroPickerHint: "Мангастай энэ дүрээр тулна.",
  multiplayerTitle: "Найзтайгаа тулах",
  multiplayerDesc:
    "Хоёр тоглогч тус тусын багцаасаа асуулт хүлээн авч, шууд тулна.",
  comingSoon: "Тун удахгүй",
  battlePoints: [
    "4 сонголттой асуулт",
    "10 секундын хязгаар",
    "Амь, цуврал, критикал цохилт",
  ],
  battleLocked: (n: number) => `Тулаанд хамгийн багадаа ${n} үг хэрэгтэй`,
  continueBattle: "Дараагийн дайсан",
  monstersDefeated: (n: number) => `${n} дайсан устгалаа`,
  stopBattle: "Тулаан зогсоох",
  retryBattle: "Дахин оролдох",
  victoryTitle: "Ялалт!",
  defeatTitle: "Ялагдал",
  clearedTitle: "Өнөөдрийн ажил дууслаа",
  clearedDesc: "Бүх үгээ давтлаа",
  critLabel: "КРИТИКАЛ ЦОХИЛТ!",
  evadedLabel: "ЗАЙЛСХИЙВ!",
  armorBlockedLabel: "ХАМГААЛАЛТ ХААЛАА!",
  timeUpLabel: "ЦАГ ДУУСЛАА!",
  armorGainedLabel: "Хамгаалалт олдлоо",
  // Arena chrome: leave, pause, and the running kill count.
  exitBattle: "Буцах",
  pauseBattle: "Түр зогсоох",
  resumeBattle: "Үргэлжлүүлэх",
  pausedTitle: "Түр зогсов",
  // No longer mentions the speed cap: that used to be a pause-only rule, and
  // now applies to every battle answer, so saying it here read as a penalty
  // for pausing.
  pausedDesc: "Цаг зогслоо. Үргэлжлүүлэхэд яг эндээсээ цааш явна.",
  killCount: (n: number) => `${n} устгав`,
  victoryFlag: "ДАЙСАН УНАЛАА!",
  // Result screen. Short noun labels for the stat tiles — the existing
  // sessionCompleteDesc/monstersDefeated strings are sentence-shaped and read
  // badly under a big number.
  resultKicker: "Тулааны дүн",
  resultWords: "Давтсан үг",
  resultCorrect: "Зөв хариулт",
  resultBestStreak: "Дээд цуврал",
  resultCrits: "Критикал цохилт",
  noMonsterDefeated: "Энэ дайсныг дийлсэнгүй",
  victoryDesc: "Унагасан дайснуудаа доор харна уу.",
  // States the one thing a defeat screen must not leave ambiguous: retrying
  // does not un-review the words already answered (see handleRetry).
  defeatDesc:
    "Амь дуусав. Хариулсан үгс аль хэдийн хадгалагдсан — дахин орвол үлдсэн үгнээс үргэлжилнэ.",
  statTotalWords: "Нийт үг",
  statTotalDecks: "Багц",
  statDueToday: "Өнөөдөр давтах",
  dueHeldBack: (n: number) => `Өдрийн хязгаараас ${n} үг хойшлов`,
  statMastered: "Эзэмшсэн (A+B)",
  statStreak: "Дараалсан өдөр",
  statNewWeek: (n: number) => `Сүүлийн 7 хоногт ${n} үг нэмэгдсэн`,
  streakDays: (n: number) => `${n} өдөр`,
  streakFreezes: (n: number) => `${n} хамгаалалттай`,
  overallGradeTitle: "Нийт түвшин",
  weekdayTitle: "Гараг тус бүрийн давталт",
  weekdaySummary: (n: number) => `Сүүлийн хагас жилд нийт ${n} давталт`,
  perWeekAvg: (n: number) => `7 хоногт дунджаар ${n}`,
  todayLabel: "Өнөөдөр",
  deckBreakdownTitle: "Багц тус бүрээр",
  colDeck: "Багц",
  colWords: "Үг",
  colDue: "Давтах",
  colMastered: "Эзэмшсэн",
  noStatsData: "Одоогоор өгөгдөл алга. Багц үүсгээд үг нэмнэ үү.",
  loadingStats: "Тооцоолж байна…",
  // Dashboard hero + heatmap
  streakLabel: "Дараалсан өдөр",
  bestStreak: (n: number) => `Хамгийн урт: ${n} өдөр`,
  masteredRingLabel: "Эзэмшсэн хувь",
  goalRingLabel: "Шинэ үгийн зорилго",
  goalRingEdit: "Зорилго өөрчлөх",
  addedRingLabel: "Өнөөдөр нэмэгдсэн",
  addedTodayCta: (n: number) => `Өнөөдөр ${n} үг нэмлээ`,
  addedTodayNone: "Өнөөдөр шинэ үг нэмээгүй байна",
  heatmapTitle: "Давталтын хуанли",
  addedHeatmapTitle: "Үг нэмсэн хуанли",
  heatmapSummary: (totalLabel: string, days: number) =>
    `Сүүлийн хагас жилд ${totalLabel} · ${days} өдөр`,
  reviewsN: (n: number) => `${n} давталт`,
  wordsN: (n: number) => `${n} үг`,
  less: "Бага",
  more: "Их",
  growthTitle: (d: number) => `Сүүлийн ${d} хоногийн өсөлт`,
  wordsUnit: "үг",
  reviewsThisWeek: "Энэ 7 хоногийн давталт",
  statBestStreak: "Хамгийн урт цуврал",
  migrationHint:
    "Идэвхийн хуанли бүрэн ажиллахын тулд 0005_review_log.sql-г Supabase дээрээ ажиллуулна уу.",
  saveFailed: "Хариултыг хадгалж чадсангүй. Дахин оролдоно уу.",

  // Review-mode modal. The dashboard's "Бүгдийг нь давтах" used to link
  // straight to /decks/practice, so the classic screen was the only mode
  // reachable from the two places people actually start a session from —
  // Monster Hunt existed but you had to know to go looking for it.
  closeLabel: "Хаах",
  moreModeOptions: "Багц сонгох, баатраа солих",
  lockedBadge: "Түгжээтэй",
  // Quick add (dashboard). The full add form lives inside a deck; this is the
  // same fields with a deck picker on top, so adding a word you just met
  // doesn't mean navigating away from the dashboard first.
  quickAdd: "Үг нэмэх",
  quickAddTitle: "Шинэ үг нэмэх",
  quickAddDeckLabel: "Аль багц руу",
  quickAddNoDecks: "Үг нэмэхийн тулд эхлээд багц үүсгэнэ үү.",
  quickAddSaveFailed: "Үгийг хадгалж чадсангүй.",
  quickAddedCount: (n: number) => `${n} үг нэмлээ`,
  quickAddDone: "Дуусгах",
  // New-word daily goal (GoalModal)
  goalModalTitle: "Өдрийн шинэ үгийн зорилго",
  goalModalDesc: "Өдөрт хэдэн шинэ үг сурахыг зорих вэ?",
  goalModalLabel: "Шинэ үг / өдөр",
  goalSaveFailed: "Зорилгыг хадгалж чадсангүй. Дахин оролдоно уу.",
  // Word spotlight
  spotlightTitle: "Таны үгсээс",
  spotlightAnother: "Өөр үг",
  spotlightOpenDeck: "Багц руу очих",
  spotlightNoMeaning: "Утга оруулаагүй байна",

  // PvP duel (PVP.md). multiplayerTitle/-Desc above are reused for the mode
  // rows; these are the mode's own screens.
  duelKicker: "Тулаан",
  duelLobbyTitle: "Хэнтэй тулах вэ?",
  duelBotSection: "Боттой тулах",
  duelBotDesc: "Хүлээх шаардлагагүй. Гурван түвшин.",
  duelBotRookie: "Дасгалжигч",
  duelBotRookieDesc: "Удаан бөгөөд олон алддаг.",
  duelBotRival: "Өрсөлдөгч",
  duelBotRivalDesc: "Тэнцүү хиртэй тулаан.",
  duelBotMaster: "Мастер",
  duelBotMasterDesc: "Хурдан, бараг алддаггүй.",
  duelFriendSection: "Найзтайгаа тулах",
  duelCreate: "Тулаан үүсгэх",
  duelJoin: "Кодоор нэгдэх",
  duelCodeLabel: "Тулааны код",
  duelCodePlaceholder: "ЖИШЭЭ: 7K2Q",
  duelCodeShare: "Энэ кодыг найздаа явуулаарай.",
  duelWaitingGuest: "Найзаа хүлээж байна…",
  duelJoinFailed: "Ийм кодтой тулаан олдсонгүй, эсвэл аль хэдийн эхэлсэн байна.",
  duelCreateFailed: "Тулаан үүсгэж чадсангүй.",
  duelCancel: "Тулааныг цуцлах",
  duelYou: "Та",
  duelRoundOf: (n: number, total: number) => `${n} / ${total} тойрог`,
  duelWaitingAnswer: "Өрсөлдөгчийг хүлээж байна…",
  duelOpponentAnswered: "Өрсөлдөгч хариуллаа",
  duelOpponentThinking: "Өрсөлдөгч бодож байна…",
  duelStreakLabel: (n: number) => `${n} дараалан`,
  duelWon: "Ялалт!",
  duelLost: "Ялагдал",
  duelDraw: "Тэнцлээ",
  duelWonDesc: "Өрсөлдөгчөө дийллээ.",
  duelLostDesc: "Энэ удаад бүтсэнгүй. Дахин оролдоорой.",
  duelDrawDesc: "Хоёулаа тэнцүү үлдлээ.",
  duelRematch: "Дахин тулах",
  duelResultRounds: "Тойрог",
  duelResultCorrect: "Зөв хариулт",
  duelResultBestStreak: "Дээд цуврал",
  duelResultDamage: "Хийсэн хохирол",
  duelTimedOut: "Хоцорлоо",
  duelNotScheduled:
    "Тулааны хариултууд давтлагын хуваарьт нөлөөлөхгүй — зөвхөн тэмдэглэгдэнэ.",
  duelLoading: "Тулаан бэлдэж байна…",
  duelLoadFailed: "Тулааны үгсийг ачаалж чадсангүй.",
  duelOpponentLeft: "Өрсөлдөгч гарлаа.",
  duelLeaveTitle: "Тулаанаас гарах уу?",
  duelLeaveDesc: "Гарвал энэ тулаанд ялагдсанд тооцогдоно.",

  // Friends, leaderboard, XP/ELO (0026). Same copy as mobile's strings.dart.
  friendsNav: "Найзууд",
  socialTitle: "Найзууд",
  socialTabFriends: "Найзууд",
  socialTabBoard: "Тэргүүлэгчид",
  socialPickHandle: "Хэрэглэгчийн нэрээ сонгоно уу",
  socialPickHandleDesc: "Найзууд тань энэ нэрээр л таныг хайж олно. И-мэйл хэзээ ч харагдахгүй.",
  socialHandleLabel: "Хэрэглэгчийн нэр",
  socialSave: "Хадгалах",
  socialHandleFormat: "3–20 тэмдэгт: a–z, 0–9, _",
  socialHandleTaken: "Энэ нэрийг өөр хүн авсан байна.",
  socialHandleFailed: "Хадгалж чадсангүй.",
  socialCopyHandle: "Хуулах",
  socialCopied: "Хуулагдлаа",
  socialAddFriend: "Найз нэмэх",
  socialAddHint: "@хэрэглэгчийн нэр",
  socialAdd: "Нэмэх",
  socialSent: "Хүсэлт илгээлээ.",
  socialAccepted: "Найз боллоо!",
  socialAlready: "Аль хэдийн найз эсвэл хүсэлт илгээсэн байна.",
  socialNotFound: "Ийм хэрэглэгч олдсонгүй.",
  socialSelf: "Өөрийгөө нэмэх боломжгүй.",
  socialRequests: "Найзын хүсэлт",
  socialOutgoing: "Хариу хүлээж байна",
  socialAccept: "Зөвшөөрөх",
  socialDecline: "Татгалзах",
  socialCancelRequest: "Цуцлах",
  socialRemove: "Найзаас хасах",
  socialNoFriends: "Одоохондоо найз алга. Хэрэглэгчийн нэрээр нь нэмээрэй.",
  socialHidden: "Идэвхээ нуусан",
  socialYou: "Та",
  socialLevel: (lv: number) => `Түвшин ${lv}`,
  socialXp: (xp: number) => `${xp} XP`,
  socialAddedToday: (n: number) => `+${n} үг нэмсэн`,
  socialReviewedToday: (n: number) => `${n} давталт`,
  socialWordsLearned: (n: number) => `${n} үг сурсан`,
  socialKanjiLearned: (n: number) => `${n} ханз`,
  socialElo: (e: number) => `ELO ${e}`,
  socialToday: "Өнөөдөр",
  socialBoardWeek: "7 хоног",
  socialBoardTotal: "Нийт XP",
  socialBoardElo: "ELO",
  socialScopeFriends: "Найзууд",
  socialScopeAll: "Бүгд",
  socialGlobalNote: "Бүх хэрэглэгч — зөвхөн хэрэглэгчийн нэр, оноо харагдана. Идэвхээ нуувал энд гарахгүй.",
  socialGlobalNeedHandle: "Энд гарахын тулд Найзууд хэсэгт хэрэглэгчийн нэрээ сонгоорой.",
  socialFriendTag: "найз",
  socialBoardEmpty: "Найзуудаа нэмээд хамт өрсөлдөөрэй.",
  socialBoardEloNote: "ELO зөвхөн найзтайгаа хийсэн онлайн тулаанаар өөрчлөгдөнө.",
  socialXpNote: "XP: давталт, Монстр агнах, ханз бичих, шинэ үг, тулаан.",
  socialUnavailable: "Найзын функц одоогоор боломжгүй (серверт 0026 шилжилт хийгдээгүй эсвэл интернэт алга).",
  socialShareSetting: "Идэвхээ найзуудад харуулах",
  socialShareSettingDesc: "Унтраавал найзууд тань зөвхөн нэрийг тань харна.",
  socialChallenge: "Тулаанд урих",

  // Kanji writing lessons — same copy as mobile's strings.dart.
  writingTitle: "Ханз бичих",
  writingDesc: "Ханз бүрийг дагаж, хагас харж, санаж бичих хичээл. Хуваарь өөрчлөгдөхгүй.",
  writingSetupDeck: "Багц",
  writingAllDecks: "Бүх багц",
  writingByWord: "Үгээр",
  writingByKanji: "Ханзаар",
  writingPickNew: "Шинэ ханзтай",
  writingPickAll: "Бүгд",
  writingPickNone: "Цэвэрлэх",
  writingLearnedLegend: "✓ — сурсан ханз",
  writingStartLesson: (n: number) => `Хичээл эхлэх (${n} үг)`,
  writingKanjiSelected: (k: number, w: number) => `${k} ханз → ${w} үг`,
  writingNoKanji: "Ханзтай үг алга байна.",
  writingPreparing: "Хичээл бэлдэж байна…",
  writingStepTrace: "Шинэ ханз — дарааллыг ажиглаад дагаж бичээрэй",
  writingStepPartial: "Зарим зурлага харагдана — бүтнээр нь бичээрэй",
  writingStepBlank: "Одоо санаж бичээрэй",
  writingStepWord: "Үгийг бүтнээр нь бичээрэй",
  writingCheck: "Шалгах",
  writingUndo: "Буцаах",
  writingClear: "Арилгах",
  writingReplay: "Дахин үзүүлэх",
  writingReveal: "Хариуг харах",
  writingCorrect: "Зөв!",
  writingWrong: "Буруу",
  writingContinue: "Үргэлжлүүлэх",
  writingSkip: "Алгасах",
  writingRetry: "Дахин бичих",
  writingLessonDone: "Хичээл дууслаа!",
  writingStatWords: "Үг",
  writingStatNewKanji: "Шинэ ханз",
  writingStatAccuracy: "Анхны оролдлогоор",
  writingNextLesson: "Дараагийн хичээл",
  writingBackToPick: "Өөр үг сонгох",
  writingFinish: "Дуусгах",
  writingStrokeCount: (drawn: number, expected: number) => `Зурлагын тоо буруу: ${drawn} / ${expected}`,
  writingStrokeOrder: (i: number, j: number) => `${i}-р зурлагын дараалал буруу — энэ ${j}-р зурлага`,
  writingStrokeDirection: (i: number) => `${i}-р зурлагыг эсрэг чиглэлд татсан`,
  writingStrokeShape: (i: number) => `${i}-р зурлагын хэлбэр эсвэл байрлал буруу`,
  writingNoStrokeData: "Энэ ханзны зурлагын өгөгдөл ачаалагдсангүй — хариутай харьцуулаад өөрөө шалгаарай.",
  writingSelfRight: "Зөв бичсэн",
  writingSelfWrong: "Буруу байна",
  kanjiVgCredit: "Зурлагын дараалал: KanjiVG (CC BY-SA 3.0)",

  // Public deck links (/share/<token>) and story-card images.
  shareDeck: "Хуваалцах",
  shareDeckTitle: "Багцыг хуваалцах",
  shareDeckDesc: "Холбоосыг авсан хэн ч бүртгэлгүйгээр үгсийг харж, давтаж тоглож чадна. Таны нэр, давтлагын түүх харагдахгүй. Холбоос 24 цаг хүчинтэй.",
  shareLinkOn: "Холбоос идэвхтэй",
  shareLinkOff: "Холбоос хаалттай",
  shareLinkEnable: "Холбоос үүсгэх",
  shareLinkDisable: "Холбоосыг хаах",
  shareLinkDisableHint: "Холбоос 24 цагийн дараа өөрөө хаагдана. Хаавал шууд ажиллахаа болино; дахин нээвэл шинэ холбоос үүснэ.",
  shareExpiresIn: (min: number) =>
    min >= 60 ? `${Math.floor(min / 60)} ц ${min % 60} мин үлдсэн` : `${min} мин үлдсэн`,
  shareCopy: "Хуулах",
  shareCopied: "Хуулсан!",
  shareStoryImage: "Story зураг",
  shareFailed: "Хуваалцах тохиргоо хадгалагдсангүй",
  shareToday: "Өнөөдрийг хуваалцах",
  shareTodayTitle: "Өнөөдрийн үгс",
  shareTodayEmpty: "Өнөөдөр зөв хариулсан үг алга байна — эхлээд давтаад ирээрэй.",
  shareImageShare: "Хуваалцах",
  shareImageDownload: "Татах",
  shareImageHint: (w: number, h: number) => `Утасны дэлгэцийн хэмжээтэй (${w}×${h}) — Instagram, Facebook story-д бүтэн дүүрнэ.`,
  storyTodayHeading: "Өнөөдөр сурсан үгс",
  storyTodayStats: (recalled: number, added: number) =>
    added > 0 ? `${recalled} үг санасан · ${added} шинэ үг нэмсэн` : `${recalled} үг санасан`,
  storyDeckHeading: "Энэ багцыг туршаад үз",
  storyDeckStats: (n: number) => `${n} үг · бүртгэлгүйгээр тоглоно`,
  storyMore: (n: number) => `+${n} үг`,
  storyStreak: (n: number) => `🔥 ${n} өдөр дараалан`,
  // The shared page itself.
  sharedBy: "Хуваалцсан багц",
  sharedWords: (n: number) => `${n} үг`,
  sharedPlayHunt: "Мангас агнах",
  sharedPlayHuntDesc: "Цагтай, 4 сонголттой тулаан",
  sharedPlayCards: "Карт эргүүлэх",
  sharedPlayCardsDesc: "Үгийг хараад санаж, эргүүлж шалга",
  sharedHuntNeedsWords: "Тулаанд дор хаяж 4 үг хэрэгтэй",
  sharedTrialBanner: "Туршилт — юу ч хадгалагдахгүй. Ахицаа хадгалахыг хүсвэл бүртгүүлээрэй.",
  sharedSignUp: "Үнэгүй бүртгүүлэх",
  sharedSignInToCopy: "Нэвтэрч миний багцад нэмэх",
  sharedCopy: "Миний багцад нэмэх",
  sharedCopying: "Нэмж байна…",
  sharedCopied: "Нэмэгдлээ — багц руу очих",
  sharedCopyFailed: "Нэмж чадсангүй",
  sharedBack: "Багц руу буцах",
  sharedPitch: "Үгээ давталтын системээр цээжил — бүртгүүлбэл ахиц тань хадгалагдана.",
  sharedNotFound: "Энэ холбоосын хугацаа дууссан эсвэл хаагдсан байна.",
  sharedCardsShow: "Хариуг харах",
  sharedCardsAgain: "Дахиад",
  sharedCardsKnew: "Мэдсэн",
  sharedCardsDone: "Бүх үгийг давтлаа!",
  sharedCardsDoneDesc: (n: number) => `${n} хариулт. Бүртгүүлбэл үг бүрийг яг мартах дөхсөн үед тань давтуулна.`,
  sharedCardsRestart: "Дахин эхлэх",

  // Leaderboard: friends only, with your online duels against each friend.
  socialBoardFriendsOnly: "Найзуудын дундах эрэмбэ",
  socialVsYou: (rec: string) => `Тантай ${rec}`,
  socialMyRecord: (rec: string) => `Онлайн ${rec}`,
  socialDraws: (n: number) => `${n} тэнцээ`,
  socialMyDuels: "Таны онлайн тулаан",
  socialDuelsWith: (name: string) => `${name}-тэй хийсэн тулаан`,
  socialNoDuels: "Одоохондоо тулалдаагүй байна.",
  socialWin: "Ялалт",
  socialLoss: "Ялагдал",
  socialDraw: "Тэнцээ",
  socialWins: "ялалт",
  socialLosses: "ялагдал",
  socialDrawsWord: "тэнцээ",
  socialLeftEarly: "дундаас гарсан",

  // Тохиргоо (settings).
  settingsTitle: "Тохиргоо",
  settingsLoadFailed: "Тохиргоог ачаалж чадсангүй.",
  settingsSignedInAs: "Нэвтэрсэн",
  settingsSaved: "Хадгаллаа",
  settingsSaveFailed: "Хадгалж чадсангүй. Дахин оролдоно уу.",
  settingsProfile: "Профайл",
  settingsChangePhoto: "Зураг солих",
  settingsRemovePhoto: "Зураг арилгах",
  settingsUploading: "Хуулж байна…",
  settingsPhotoHint: "Квадрат болгож багасгаад хадгална. Найзууд тань харна.",
  settingsPhotoType: "Зөвхөн зураг сонгоно уу.",
  settingsPhotoFailed: "Зургийг хадгалж чадсангүй.",
  settingsDisplayName: "Нэр",
  settingsEmail: "И-мэйл",
  settingsEmailHint: "Google бүртгэлээр нэвтэрсэн тул эндээс солих боломжгүй.",
  settingsAppearance: "Өнгө төрх",
  settingsAppearanceDesc: "Энэ төхөөрөмж дээр хадгалагдана.",
  themeLight: "Цайвар",
  themeDark: "Бараан",
  themeSystem: "Системийн",
  settingsLearning: "Суралцах",
  settingsLearningDesc: "Өдөр бүр хэдэн үг өгөх, өдөр хэдэн цагт шилжих.",
  settingsNewPerDay: "Шинэ үг / өдөр",
  settingsReviewsPerDay: "Давтлага / өдөр",
  settingsDayCutoff: "Шинэ өдөр эхлэх цаг",
  settingsTimezone: (tz: string) => `Цагийн бүс: ${tz} (хөтчөөс автоматаар)`,
  settingsLimitsInvalid: "Шинэ үг 0–999, давтлага 0–9999 хооронд байна.",
  settingsPrivacy: "Нууцлал",
};
