// Mongolian UI strings (all users are Mongolian).
export const T = {
  folders: "Хавтаснууд",
  allDecks: "Бүх багц",
  noFolder: "Хавтасгүй",
  newFolder: "Шинэ хавтасны нэр",
  newFolderTitle: "Шинэ хавтас нэмэх",
  emptyFolder: "хоосон",
  decks: "Багцууд",
  newDeck: "Шинэ багцын нэр",
  add: "Нэмэх",
  noDecks: "Багц алга",
  loading: "Ачааллаж байна…",
  createDeckToStart: "Эхлэхийн тулд багц үүсгэнэ үү.",
  search: "Үг хайх…",
  searchResults: "Хайлтын үр дүн",
  noResults: "Илэрц олдсонгүй",
  noWords: "Энэ багцад үг алга. Дээр нэмэх эсвэл өргөтгөлөөс хадгална уу.",
  exportApkg: ".apkg татах",
  building: "Бэлдэж байна…",
  exportFailed: "Экспорт амжилтгүй",
  delete: "Устгах",
  term: "Үг (ж: 勉強)",
  reading: "Дуудлага",
  lookingUp: "Хайж байна…",
  meaningEn: "Утга (Англи)",
  mongolian: "Монгол",
  addWord: "Үг нэмэх",
  clickToRename: "Нэр солих бол дарна уу",
  playAudio: "Дуудлага сонсох",
  removeWord: "Үг устгах",
  edit: "Засах",
  editWord: "Үг засах",
  refresh: "Шинэчлэх",
  research: "Jisho-оос дахин хайх",
  translate: "Орчуулах",
  save: "Хадгалах",
  cancel: "Болих",
  gridView: "Картаар харах",
  listView: "Жагсаалтаар харах",
  noFolderOption: "— Хавтасгүй —",
  audioFailed: "Дуу үүсгэж чадсангүй",
  deleteDeckConfirm: (n: string) =>
    `“${n}” багц болон доторх бүх үгийг устгах уу? Буцаах боломжгүй.`,
  deleteFolderConfirm: (n: string) =>
    `“${n}” хавтсыг устгах уу? Доторх багцууд устахгүй, хавтасгүй болно.`,
  duplicateWord: "Давхардсан үг",
  duplicateWordConfirm: (t: string) =>
    `“${t}” энэ багцад аль хэдийн бүртгэгдсэн байна. Дахин нэмэх үү?`,
  addAnyway: "Дахин нэмэх",
  practice: "Давтах",
  practiceAll: "Бүгдийг нь давтах",
  loadingWords: "Үгсийг ачааллаж байна…",
  noWordsDue: "Одоогоор давтах үг алга. Дараа дахин ирнэ үү!",
  showAnswer: "Хариулт харах",
  again: "Дахин",
  hard: "Хэцүү",
  good: "Сайн",
  easy: "Амархан",
  // Practice session chrome
  spaceHint: "Зай",
  exitSession: "Дуусгах",
  undo: "Буцаах",
  undoTitle: "Сүүлийн хариултыг буцаах",
  progressLabel: (done: number, total: number) => `${done} / ${total}`,
  remainingN: (n: number) => `${n} үг үлдсэн`,
  againSoon: "Одоо дахин",
  intervalMinutes: (n: number) => `${n} мин`,
  intervalDays: (n: number) => `${n} өдөр`,
  intervalMonths: (n: number) => `${n} сар`,
  intervalYears: (n: number) => `${n} жил`,
  reviewAgain: "Дахин давтах",
  sessionStatWords: "Давтсан үг",
  keyboardHint: "Зай — хариулт · 1-4 — үнэлгээ",
  sessionComplete: "Давтаж дууслаа!",
  sessionCompleteDesc: (n: number) => `Та ${n} үг дахин үзлээ.`,
  backToDecks: "Багцууд руу буцах",
  gradeTitle: "Түвшин",
  gradeNew: "Шинэ",
  dashboardNav: "Хяналтын самбар",
  decksNav: "Багцууд",
  statTotalWords: "Нийт үг",
  statTotalDecks: "Багц",
  statDueToday: "Өнөөдөр давтах",
  statMastered: "Эзэмшсэн (A+B)",
  statStreak: "Дараалсан өдөр",
  statNewWeek: (n: number) => `Сүүлийн 7 хоногт ${n} үг нэмэгдсэн`,
  streakDays: (n: number) => `${n} өдөр`,
  overallGradeTitle: "Нийт түвшин",
  weekdayTitle: "Гараг тус бүрийн давталт",
  weekdaySummary: (n: number) => `Сүүлийн хагас жилд нийт ${n} давталт`,
  perWeekAvg: (n: number) => `7 хоногт дунджаар ${n}`,
  todayLabel: "Өнөөдөр",
  deckBreakdownTitle: "Багц тус бүрээр",
  colDeck: "Багц",
  colWords: "Үг",
  colDue: "Давтах",
  colMastered: "Эзэмшсэн",
  noStatsData: "Одоогоор өгөгдөл алга. Багц үүсгээд үг нэмнэ үү.",
  loadingStats: "Тооцоолж байна…",
  // Dashboard hero + heatmap
  streakLabel: "Дараалсан өдөр",
  bestStreak: (n: number) => `Хамгийн урт: ${n} өдөр`,
  masteredRingLabel: "Эзэмшсэн хувь",
  addedTodayCta: (n: number) => `Өнөөдөр ${n} үг нэмлээ`,
  addedTodayNone: "Өнөөдөр шинэ үг нэмээгүй байна",
  heatmapTitle: "Давталтын хуанли",
  addedHeatmapTitle: "Үг нэмсэн хуанли",
  heatmapSummary: (totalLabel: string, days: number) =>
    `Сүүлийн хагас жилд ${totalLabel} · ${days} өдөр`,
  reviewsN: (n: number) => `${n} давталт`,
  wordsN: (n: number) => `${n} үг`,
  less: "Бага",
  more: "Их",
  growthTitle: (d: number) => `Сүүлийн ${d} хоногийн өсөлт`,
  wordsUnit: "үг",
  reviewsThisWeek: "Энэ 7 хоногийн давталт",
  statBestStreak: "Хамгийн урт цуврал",
  migrationHint:
    "Идэвхийн хуанли бүрэн ажиллахын тулд 0005_review_log.sql-г Supabase дээрээ ажиллуулна уу.",
  saveFailed: "Хариултыг хадгалж чадсангүй. Дахин оролдоно уу.",
};
