// Mongolian UI strings (all users are Mongolian).
export const T = {
  folders: "Хавтаснууд",
  allDecks: "Бүх багц",
  noFolder: "Хавтасгүй",
  newFolder: "Шинэ хавтасны нэр",
  newFolderTitle: "Шинэ хавтас нэмэх",
  emptyFolder: "хоосон",
  decks: "Багцууд",
  newDeck: "Шинэ багцын нэр",
  add: "Нэмэх",
  noDecks: "Багц алга",
  loading: "Ачааллаж байна…",
  createDeckToStart: "Эхлэхийн тулд багц үүсгэнэ үү.",
  search: "Үг хайх…",
  searchResults: "Хайлтын үр дүн",
  noResults: "Илэрц олдсонгүй",
  noWords: "Энэ багцад үг алга. Дээр нэмэх эсвэл өргөтгөлөөс хадгална уу.",
  exportApkg: ".apkg татах",
  building: "Бэлдэж байна…",
  exportFailed: "Экспорт амжилтгүй",
  delete: "Устгах",
  term: "Үг (ж: 勉強)",
  reading: "Дуудлага",
  lookingUp: "Хайж байна…",
  meaningEn: "Утга (Англи)",
  mongolian: "Монгол",
  addWord: "Үг нэмэх",
  clickToRename: "Нэр солих бол дарна уу",
  playAudio: "Дуудлага сонсох",
  removeWord: "Үг устгах",
  edit: "Засах",
  editWord: "Үг засах",
  refresh: "Шинэчлэх",
  research: "Jisho-оос дахин хайх",
  translate: "Орчуулах",
  save: "Хадгалах",
  cancel: "Болих",
  gridView: "Картаар харах",
  listView: "Жагсаалтаар харах",
  noFolderOption: "— Хавтасгүй —",
  audioFailed: "Дуу үүсгэж чадсангүй",
  deleteDeckConfirm: (n: string) =>
    `“${n}” багц болон доторх бүх үгийг устгах уу? Буцаах боломжгүй.`,
  deleteFolderConfirm: (n: string) =>
    `“${n}” хавтсыг устгах уу? Доторх багцууд устахгүй, хавтасгүй болно.`,
};
