// Kanji stroke data and handwriting grading for the web's writing lessons —
// a port of mobile's svg_path.dart, kanji_strokes.dart and stroke_grader.dart.
//
// The two apps must judge handwriting the same way, so both are checked
// against one fixture (fixtures/strokes.fixture.json, generated by
// mobile/test/stroke_fixture_test.dart): real KanjiVG strokes drawn cleanly,
// small, stretched and shaky, and broken on purpose — missing, extra, swapped,
// reversed and misplaced strokes — with the verdict for each.
//
// The web has no ML Kit, so the stroke check is the whole judgement here; on
// mobile it is combined with the recogniser. The stroke check is the part
// that catches mistakes (count, order, direction, placement).

export type Pt = [number, number];
export type Polyline = Pt[];

/** KanjiVG's coordinate box. */
export const KANJI_BOX = 109;

// ---- SVG path data → polyline ------------------------------------------------

const CURVE_STEPS = 16;

/**
 * Flattens path data (M, L, H, V, C, S, Q, T, Z and their relative forms —
 * what KanjiVG uses) into a polyline. Curves are sampled finely; the grader
 * resamples by arc length afterwards, so the sampling density doesn't matter.
 */
export function flattenPath(d: string): Polyline {
  const tokens = d.match(/[A-Za-z]|-?(?:\d+\.?\d*|\.\d+)(?:[eE][-+]?\d+)?/g) ?? [];
  const out: Polyline = [];
  let i = 0;
  let cmd = "";
  let cur: Pt = [0, 0];
  let start: Pt = [0, 0];
  let lastCtrl: Pt | null = null;
  let lastCmd = "";
  const isCmd = (t: string) => /^[A-Za-z]$/.test(t);
  const num = () => parseFloat(tokens[i++]);
  const pt = (rel: boolean): Pt => {
    const x = num();
    const y = num();
    return rel ? [cur[0] + x, cur[1] + y] : [x, y];
  };
  const cubic = (p0: Pt, c1: Pt, c2: Pt, p3: Pt) => {
    for (let s = 1; s <= CURVE_STEPS; s++) {
      const t = s / CURVE_STEPS;
      const u = 1 - t;
      out.push([
        u * u * u * p0[0] + 3 * u * u * t * c1[0] + 3 * u * t * t * c2[0] + t * t * t * p3[0],
        u * u * u * p0[1] + 3 * u * u * t * c1[1] + 3 * u * t * t * c2[1] + t * t * t * p3[1],
      ]);
    }
  };
  const quad = (p0: Pt, c: Pt, p2: Pt) => {
    for (let s = 1; s <= CURVE_STEPS; s++) {
      const t = s / CURVE_STEPS;
      const u = 1 - t;
      out.push([u * u * p0[0] + 2 * u * t * c[0] + t * t * p2[0], u * u * p0[1] + 2 * u * t * c[1] + t * t * p2[1]]);
    }
  };

  while (i < tokens.length) {
    if (isCmd(tokens[i])) cmd = tokens[i++];
    else if (!cmd) break;
    const rel = cmd === cmd.toLowerCase();
    switch (cmd.toUpperCase()) {
      case "M":
        cur = pt(rel);
        start = cur;
        out.push(cur);
        cmd = rel ? "l" : "L"; // further pairs are implicit linetos
        lastCtrl = null;
        break;
      case "L":
        cur = pt(rel);
        out.push(cur);
        lastCtrl = null;
        break;
      case "H": {
        const x = num();
        cur = [rel ? cur[0] + x : x, cur[1]];
        out.push(cur);
        lastCtrl = null;
        break;
      }
      case "V": {
        const y = num();
        cur = [cur[0], rel ? cur[1] + y : y];
        out.push(cur);
        lastCtrl = null;
        break;
      }
      case "C": {
        const c1 = pt(rel), c2 = pt(rel), end = pt(rel);
        cubic(cur, c1, c2, end);
        lastCtrl = c2;
        cur = end;
        break;
      }
      case "S": {
        const c1: Pt =
          lastCtrl && "CS".includes(lastCmd.toUpperCase()) ? [2 * cur[0] - lastCtrl[0], 2 * cur[1] - lastCtrl[1]] : cur;
        const c2 = pt(rel), end = pt(rel);
        cubic(cur, c1, c2, end);
        lastCtrl = c2;
        cur = end;
        break;
      }
      case "Q": {
        const c = pt(rel), end = pt(rel);
        quad(cur, c, end);
        lastCtrl = c;
        cur = end;
        break;
      }
      case "T": {
        const c: Pt =
          lastCtrl && "QT".includes(lastCmd.toUpperCase()) ? [2 * cur[0] - lastCtrl[0], 2 * cur[1] - lastCtrl[1]] : cur;
        const end = pt(rel);
        quad(cur, c, end);
        lastCtrl = c;
        cur = end;
        break;
      }
      case "Z":
        out.push(start);
        cur = start;
        lastCtrl = null;
        break;
      case "A":
        i += 5; // arcs never appear in KanjiVG; drawn as a line
        cur = pt(rel);
        out.push(cur);
        lastCtrl = null;
        break;
      default:
        i++;
    }
    lastCmd = cmd;
  }
  return out;
}

// ---- KanjiVG ---------------------------------------------------------------------

/** Stroke path data from a KanjiVG SVG, in stroke order (ids ending -s1, -s2…). */
export function parseKanjiVg(svg: string): string[] {
  const strokes: [number, string][] = [];
  for (const m of svg.matchAll(/<path\b[^>]*>/g)) {
    const tag = m[0];
    const id = /id="[^"]*-s(\d+)"/.exec(tag);
    const d = /\sd="([^"]+)"/.exec(tag);
    if (id && d) strokes.push([parseInt(id[1], 10), d[1]]);
  }
  strokes.sort((a, b) => a[0] - b[0]);
  return strokes.map((s) => s[1]);
}

/** 食 → 098df.svg: five hex digits of the code point. */
export function kanjiVgFile(char: string): string {
  return `${char.codePointAt(0)!.toString(16).padStart(5, "0")}.svg`;
}

export interface KanjiStrokes {
  char: string;
  /** Raw path data per stroke, for drawing (Path2D). */
  paths: string[];
  /** Each stroke as a polyline, for grading. */
  polylines: Polyline[];
  /** Where each stroke starts, for its stroke-order number. */
  starts: Pt[];
}

export function kanjiStrokes(char: string, paths: string[]): KanjiStrokes {
  const polylines = paths.map(flattenPath);
  return { char, paths, polylines, starts: polylines.map((p) => p[0] ?? [0, 0]) };
}

const SOURCES = [
  "https://raw.githubusercontent.com/KanjiVG/kanjivg/master/kanji/",
  "https://cdn.jsdelivr.net/gh/KanjiVG/kanjivg@master/kanji/",
];
const memory = new Map<string, KanjiStrokes | null>();

/**
 * Stroke data for a kanji: memory, then localStorage (a few KB each, so a
 * learner's whole set fits), then KanjiVG over the network. Null when there's
 * no data and no connection — the lesson then runs without a guide.
 * KanjiVG © Ulrich Apel, CC BY-SA 3.0.
 */
export async function loadKanjiStrokes(char: string): Promise<KanjiStrokes | null> {
  if (memory.has(char)) return memory.get(char)!;
  const key = `hanko.kanjivg.${kanjiVgFile(char)}`;
  let svg: string | null = null;
  try {
    svg = localStorage.getItem(key);
  } catch {}
  if (!svg) {
    for (const base of SOURCES) {
      try {
        const res = await fetch(base + kanjiVgFile(char));
        const text = res.ok ? await res.text() : "";
        // A KanjiVG file is a few KB; refuse anything that isn't one.
        if (res.ok && text.length < 256 * 1024 && text.includes("kvg:")) {
          svg = text;
          try {
            localStorage.setItem(key, svg);
          } catch {}
          break;
        }
      } catch {}
    }
  }
  const paths = svg ? parseKanjiVg(svg) : [];
  const strokes = paths.length ? kanjiStrokes(char, paths) : null;
  memory.set(char, strokes);
  return strokes;
}

// ---- Grading (stroke_grader.dart) -------------------------------------------------

export type StrokeIssue = "count" | "order" | "direction" | "shape";

export interface StrokeGrade {
  ok: boolean;
  issue: StrokeIssue | null;
  drawn: number;
  expected: number;
  /** First drawn stroke that's wrong. */
  stroke: number | null;
  /** For "order": which expected stroke the drawn one actually is. */
  expectedStroke: number | null;
}

const SAMPLES = 16;
const MEAN_TOLERANCE = 17;
const END_TOLERANCE = 26;
const SHORT_STROKE = 12;

const dist = (a: Pt, b: Pt) => Math.hypot(a[0] - b[0], a[1] - b[1]);

function length(pts: Polyline): number {
  let len = 0;
  for (let k = 1; k < pts.length; k++) len += dist(pts[k], pts[k - 1]);
  return len;
}

function centre(pts: Polyline): Pt {
  const s = pts.reduce<Pt>((a, p) => [a[0] + p[0], a[1] + p[1]], [0, 0]);
  return [s[0] / pts.length, s[1] / pts.length];
}

/** SAMPLES points evenly spaced along the stroke. */
function resample(pts: Polyline): Polyline {
  if (pts.length === 0) return Array.from({ length: SAMPLES }, () => [0, 0] as Pt);
  if (pts.length === 1) return Array.from({ length: SAMPLES }, () => pts[0]);
  const total = length(pts);
  if (total === 0) return Array.from({ length: SAMPLES }, () => pts[0]);
  const out: Polyline = [pts[0]];
  const step = total / (SAMPLES - 1);
  let walked = 0;
  let target = step;
  for (let k = 1; k < pts.length && out.length < SAMPLES; k++) {
    const a = pts[k - 1], b = pts[k];
    const seg = dist(a, b);
    while (seg > 0 && walked + seg >= target && out.length < SAMPLES - 1) {
      const t = (target - walked) / seg;
      out.push([a[0] + (b[0] - a[0]) * t, a[1] + (b[1] - a[1]) * t]);
      target += step;
    }
    walked += seg;
  }
  while (out.length < SAMPLES) out.push(pts[pts.length - 1]);
  return out;
}

function bounds(pts: Polyline) {
  let l = Infinity, t = Infinity, r = -Infinity, b = -Infinity;
  for (const p of pts) {
    l = Math.min(l, p[0]);
    t = Math.min(t, p[1]);
    r = Math.max(r, p[0]);
    b = Math.max(b, p[1]);
  }
  return Number.isFinite(l) ? { l, t, r, b } : { l: 0, t: 0, r: 0, b: 0 };
}

function normalize(drawn: Polyline[], expected: Polyline[]): Polyline[] {
  const ru = bounds(drawn.flat());
  const re = bounds(expected.flat());
  const userSize = Math.max(ru.r - ru.l, ru.b - ru.t, 1);
  const scale = Math.max(re.r - re.l, re.b - re.t) / userSize;
  const uc: Pt = [(ru.l + ru.r) / 2, (ru.t + ru.b) / 2];
  const ec: Pt = [(re.l + re.r) / 2, (re.t + re.b) / 2];
  return drawn.map((s) => resample(s.map((p): Pt => [ec[0] + (p[0] - uc[0]) * scale, ec[1] + (p[1] - uc[1]) * scale])));
}

function matches(u: Polyline, e: Polyline): boolean {
  if (length(e) < SHORT_STROKE && length(u) < SHORT_STROKE * 1.6) {
    return dist(centre(u), centre(e)) < END_TOLERANCE;
  }
  let sum = 0;
  for (let k = 0; k < SAMPLES; k++) sum += dist(u[k], e[k]);
  return sum / SAMPLES < MEAN_TOLERANCE && dist(u[0], e[0]) < END_TOLERANCE && dist(u[SAMPLES - 1], e[SAMPLES - 1]) < END_TOLERANCE;
}

/**
 * Grades a drawing (pad coordinates, one point list per stroke) against the
 * kanji's strokes. The drawing is scaled and centred onto the kanji's own
 * bounds first, so size and position on the pad don't matter.
 */
export function gradeStrokes(drawn: Polyline[], expected: Polyline[]): StrokeGrade {
  const d = drawn.filter((s) => s.length > 0);
  const base = { drawn: d.length, expected: expected.length };
  if (d.length !== expected.length) return { ok: false, issue: "count", stroke: null, expectedStroke: null, ...base };
  const user = normalize(d, expected);
  const exp = expected.map(resample);
  for (let i = 0; i < user.length; i++) {
    if (matches(user[i], exp[i])) continue;
    for (let j = 0; j < exp.length; j++) {
      if (j !== i && matches(user[i], exp[j])) {
        return { ok: false, issue: "order", stroke: i, expectedStroke: j, ...base };
      }
    }
    const issue: StrokeIssue = matches([...user[i]].reverse(), exp[i]) ? "direction" : "shape";
    return { ok: false, issue, stroke: i, expectedStroke: null, ...base };
  }
  return { ok: true, issue: null, stroke: null, expectedStroke: null, ...base };
}
