// Generated by the Phase 0 asset-reorg pass — do not hand-edit.
// Regenerate by re-running the reorg script if the character packs under
// web/public/battle/characters/ ever change. Each entry's frame count is
// read directly from the actual PNG width (width / 100), since frame count
// varies per character AND per state — there is no constant to hardcode.
//
// Every character is guaranteed to have `idle` (the two flying characters,
// bat and hellbat, have no ground-idle pose in the source pack — their
// "Flying" animation was mapped to idle instead, since that IS their
// resting state).

export type SpriteState =
  | "idle" | "walk" | "attack01" | "attack02" | "attack03" | "hurt" | "death" | "block";

export interface SpriteMeta {
  frames: number;
}

export const SPRITES: Record<string, Partial<Record<SpriteState, SpriteMeta>>> = {
  "archer": { idle: { frames: 6 }, walk: { frames: 8 }, attack01: { frames: 9 }, attack02: { frames: 12 }, hurt: { frames: 4 }, death: { frames: 4 } },
  "armored-axeman": { idle: { frames: 6 }, walk: { frames: 8 }, attack01: { frames: 9 }, attack02: { frames: 9 }, attack03: { frames: 12 }, hurt: { frames: 4 }, death: { frames: 4 } },
  "armored-orc": { idle: { frames: 6 }, walk: { frames: 8 }, attack01: { frames: 7 }, attack02: { frames: 8 }, attack03: { frames: 9 }, hurt: { frames: 4 }, death: { frames: 4 }, block: { frames: 4 } },
  "armored-skeleton": { idle: { frames: 6 }, walk: { frames: 8 }, attack01: { frames: 8 }, attack02: { frames: 9 }, hurt: { frames: 4 }, death: { frames: 4 } },
  "bat": { idle: { frames: 6 }, attack01: { frames: 6 }, attack02: { frames: 7 }, hurt: { frames: 4 }, death: { frames: 4 } },
  "black-knight-a": { idle: { frames: 6 }, walk: { frames: 8 }, attack01: { frames: 16 }, attack02: { frames: 15 }, attack03: { frames: 15 }, hurt: { frames: 4 }, death: { frames: 4 } },
  "black-knight-b": { idle: { frames: 6 }, walk: { frames: 8 }, attack01: { frames: 7 }, attack02: { frames: 8 }, attack03: { frames: 9 }, hurt: { frames: 4 }, death: { frames: 4 }, block: { frames: 4 } },
  "black-knight-c": { idle: { frames: 6 }, walk: { frames: 8 }, attack01: { frames: 8 }, attack02: { frames: 9 }, attack03: { frames: 13 }, hurt: { frames: 4 }, death: { frames: 10 } },
  "blood-monster-a": { idle: { frames: 6 }, walk: { frames: 8 }, attack01: { frames: 8 }, attack02: { frames: 8 }, hurt: { frames: 4 }, death: { frames: 4 } },
  "blood-monster-b": { idle: { frames: 6 }, attack01: { frames: 8 }, attack02: { frames: 9 }, hurt: { frames: 4 }, death: { frames: 6 } },
  "demon-a": { idle: { frames: 6 }, walk: { frames: 8 }, attack01: { frames: 7 }, attack02: { frames: 7 }, hurt: { frames: 4 }, death: { frames: 4 } },
  "demon-b": { idle: { frames: 6 }, walk: { frames: 8 }, attack01: { frames: 9 }, attack02: { frames: 6 }, hurt: { frames: 4 }, death: { frames: 4 } },
  "demon-c": { idle: { frames: 6 }, walk: { frames: 6 }, attack01: { frames: 6 }, attack02: { frames: 6 }, hurt: { frames: 4 }, death: { frames: 4 } },
  "demon-d": { idle: { frames: 6 }, walk: { frames: 8 }, attack01: { frames: 11 }, attack02: { frames: 18 }, attack03: { frames: 12 }, hurt: { frames: 4 }, death: { frames: 4 } },
  "demon-e": { idle: { frames: 6 }, walk: { frames: 8 }, attack01: { frames: 8 }, attack02: { frames: 13 }, attack03: { frames: 8 }, hurt: { frames: 4 }, death: { frames: 4 } },
  "demoness-a": { idle: { frames: 6 }, walk: { frames: 8 }, attack01: { frames: 9 }, attack02: { frames: 15 }, attack03: { frames: 16 }, hurt: { frames: 4 }, death: { frames: 4 } },
  "demoness-b": { idle: { frames: 6 }, walk: { frames: 6 }, attack01: { frames: 8 }, attack02: { frames: 8 }, hurt: { frames: 4 }, death: { frames: 4 } },
  "elite-orc": { idle: { frames: 6 }, walk: { frames: 8 }, attack01: { frames: 7 }, attack02: { frames: 11 }, attack03: { frames: 9 }, hurt: { frames: 4 }, death: { frames: 4 } },
  "eyeball-monster": { idle: { frames: 6 }, walk: { frames: 6 }, attack01: { frames: 8 }, attack02: { frames: 8 }, attack03: { frames: 6 }, hurt: { frames: 4 }, death: { frames: 4 } },
  "flame-golem": { idle: { frames: 6 }, walk: { frames: 12 }, attack01: { frames: 9 }, attack02: { frames: 9 }, attack03: { frames: 9 }, hurt: { frames: 4 }, death: { frames: 6 } },
  "ghostfire": { idle: { frames: 6 }, attack01: { frames: 6 }, attack02: { frames: 7 }, hurt: { frames: 4 }, death: { frames: 6 } },
  "greatsword-skeleton": { idle: { frames: 6 }, walk: { frames: 9 }, attack01: { frames: 9 }, attack02: { frames: 12 }, attack03: { frames: 8 }, hurt: { frames: 4 }, death: { frames: 4 } },
  "hellbat": { idle: { frames: 6 }, attack01: { frames: 6 }, attack02: { frames: 7 }, hurt: { frames: 4 }, death: { frames: 4 } },
  "hellhound": { idle: { frames: 6 }, walk: { frames: 8 }, attack01: { frames: 8 }, attack02: { frames: 8 }, hurt: { frames: 4 }, death: { frames: 4 } },
  "knight": { idle: { frames: 6 }, walk: { frames: 8 }, attack01: { frames: 7 }, attack02: { frames: 10 }, attack03: { frames: 11 }, hurt: { frames: 4 }, death: { frames: 4 }, block: { frames: 4 } },
  "knight-templar": { idle: { frames: 6 }, walk: { frames: 8 }, attack01: { frames: 7 }, attack02: { frames: 8 }, attack03: { frames: 11 }, hurt: { frames: 4 }, death: { frames: 4 }, block: { frames: 4 } },
  "lancer": { idle: { frames: 6 }, walk: { frames: 8 }, attack01: { frames: 6 }, attack02: { frames: 9 }, attack03: { frames: 8 }, hurt: { frames: 4 }, death: { frames: 4 } },
  "lava-slime": { idle: { frames: 6 }, walk: { frames: 6 }, attack01: { frames: 6 }, attack02: { frames: 9 }, hurt: { frames: 4 }, death: { frames: 4 } },
  "minotaur": { idle: { frames: 6 }, walk: { frames: 8 }, attack01: { frames: 8 }, attack02: { frames: 7 }, attack03: { frames: 7 }, hurt: { frames: 4 }, death: { frames: 4 } },
  "necromancer": { idle: { frames: 6 }, walk: { frames: 6 }, attack01: { frames: 9 }, attack02: { frames: 10 }, hurt: { frames: 4 }, death: { frames: 9 } },
  "orc": { idle: { frames: 6 }, walk: { frames: 8 }, attack01: { frames: 6 }, attack02: { frames: 6 }, hurt: { frames: 4 }, death: { frames: 4 } },
  "orc-rider": { idle: { frames: 6 }, walk: { frames: 8 }, attack01: { frames: 8 }, attack02: { frames: 9 }, attack03: { frames: 11 }, hurt: { frames: 4 }, death: { frames: 4 }, block: { frames: 4 } },
  "priest": { idle: { frames: 6 }, walk: { frames: 8 }, attack01: { frames: 9 }, hurt: { frames: 4 }, death: { frames: 4 } },
  "skeleton": { idle: { frames: 6 }, walk: { frames: 8 }, attack01: { frames: 6 }, attack02: { frames: 7 }, hurt: { frames: 4 }, death: { frames: 4 }, block: { frames: 4 } },
  "skeleton-archer": { idle: { frames: 6 }, walk: { frames: 8 }, attack01: { frames: 9 }, hurt: { frames: 4 }, death: { frames: 4 } },
  "slime": { idle: { frames: 6 }, walk: { frames: 6 }, attack01: { frames: 6 }, attack02: { frames: 12 }, hurt: { frames: 4 }, death: { frames: 4 } },
  "soldier": { idle: { frames: 6 }, walk: { frames: 8 }, attack01: { frames: 6 }, attack02: { frames: 6 }, attack03: { frames: 9 }, hurt: { frames: 4 }, death: { frames: 4 } },
  "swordsman": { idle: { frames: 6 }, walk: { frames: 8 }, attack01: { frames: 7 }, attack02: { frames: 15 }, attack03: { frames: 12 }, hurt: { frames: 5 }, death: { frames: 4 } },
  "warlock": { idle: { frames: 6 }, walk: { frames: 8 }, attack01: { frames: 7 }, attack02: { frames: 6 }, hurt: { frames: 4 }, death: { frames: 11 } },
  "werebear": { idle: { frames: 6 }, walk: { frames: 8 }, attack01: { frames: 9 }, attack02: { frames: 13 }, attack03: { frames: 9 }, hurt: { frames: 4 }, death: { frames: 4 } },
  "werewolf": { idle: { frames: 6 }, walk: { frames: 8 }, attack01: { frames: 9 }, attack02: { frames: 13 }, hurt: { frames: 4 }, death: { frames: 4 } },
  "wizard": { idle: { frames: 6 }, walk: { frames: 8 }, attack01: { frames: 6 }, attack02: { frames: 9 }, hurt: { frames: 4 }, death: { frames: 4 } },
};

// Display names, for any future character-select UI.
export const CHARACTER_NAMES: Record<string, string> = {
  "archer": "Archer",
  "armored-axeman": "Armored Axeman",
  "armored-orc": "Armored Orc",
  "armored-skeleton": "Armored Skeleton",
  "bat": "Bat",
  "black-knight-a": "Black Knight_A",
  "black-knight-b": "Black Knight_B",
  "black-knight-c": "Black Knight_C",
  "blood-monster-a": "Blood Monster_A",
  "blood-monster-b": "Blood Monster_B",
  "demon-a": "Demon_A",
  "demon-b": "Demon_B",
  "demon-c": "Demon_C",
  "demon-d": "Demon_D",
  "demon-e": "Demon_E",
  "demoness-a": "Demoness_A",
  "demoness-b": "Demoness_B",
  "elite-orc": "Elite Orc",
  "eyeball-monster": "Eyeball Monster",
  "flame-golem": "Flame Golem",
  "ghostfire": "Ghostfire",
  "greatsword-skeleton": "Greatsword Skeleton",
  "hellbat": "Hellbat",
  "hellhound": "Hellhound",
  "knight": "Knight",
  "knight-templar": "Knight Templar",
  "lancer": "Lancer",
  "lava-slime": "Lava Slime",
  "minotaur": "Minotaur",
  "necromancer": "Necromancer",
  "orc": "Orc",
  "orc-rider": "Orc rider",
  "priest": "Priest",
  "skeleton": "Skeleton",
  "skeleton-archer": "Skeleton Archer",
  "slime": "Slime",
  "soldier": "Soldier",
  "swordsman": "Swordsman",
  "warlock": "Warlock",
  "werebear": "Werebear",
  "werewolf": "Werewolf",
  "wizard": "Wizard",
};

