// Generated by the Phase 0 asset-reorg pass — do not hand-edit.
// Regenerate by re-running the reorg script if the character packs under
// web/public/battle/characters/ ever change. Each entry's frame count is
// read directly from the actual PNG width (width / 100), since frame count
// varies per character AND per state — there is no constant to hardcode.
//
// Every character is guaranteed to have `idle` (the two flying characters,
// bat and hellbat, have no ground-idle pose in the source pack — their
// "Flying" animation was mapped to idle instead, since that IS their
// resting state).

export type SpriteState =
  | "idle" | "walk" | "attack01" | "attack02" | "attack03" | "hurt" | "death" | "block";

// Clip lengths, shared so nothing has to guess at them. One-shots (attacks,
// hurt, death) run faster than the looping idle/walk — a 6-frame idle at
// attack speed reads as jittery rather than calm.
//
// Exported because BattleArena schedules against them: a projectile is only
// released once its thrower has finished the throw, so the launch delay IS
// this number. Duplicating it as a literal there is exactly how the two would
// drift apart.
export const ONE_SHOT_MS = 500;
export const LOOP_MS = 900;

export interface SpriteMeta {
  frames: number;
}

export const SPRITES: Record<string, Partial<Record<SpriteState, SpriteMeta>>> = {
  "archer": { idle: { frames: 6 }, walk: { frames: 8 }, attack01: { frames: 9 }, attack02: { frames: 12 }, hurt: { frames: 4 }, death: { frames: 4 } },
  "armored-axeman": { idle: { frames: 6 }, walk: { frames: 8 }, attack01: { frames: 9 }, attack02: { frames: 9 }, attack03: { frames: 12 }, hurt: { frames: 4 }, death: { frames: 4 } },
  "armored-orc": { idle: { frames: 6 }, walk: { frames: 8 }, attack01: { frames: 7 }, attack02: { frames: 8 }, attack03: { frames: 9 }, hurt: { frames: 4 }, death: { frames: 4 }, block: { frames: 4 } },
  "armored-skeleton": { idle: { frames: 6 }, walk: { frames: 8 }, attack01: { frames: 8 }, attack02: { frames: 9 }, hurt: { frames: 4 }, death: { frames: 4 } },
  "bat": { idle: { frames: 6 }, attack01: { frames: 6 }, attack02: { frames: 7 }, hurt: { frames: 4 }, death: { frames: 4 } },
  "black-knight-a": { idle: { frames: 6 }, walk: { frames: 8 }, attack01: { frames: 16 }, attack02: { frames: 15 }, attack03: { frames: 15 }, hurt: { frames: 4 }, death: { frames: 4 } },
  "black-knight-b": { idle: { frames: 6 }, walk: { frames: 8 }, attack01: { frames: 7 }, attack02: { frames: 8 }, attack03: { frames: 9 }, hurt: { frames: 4 }, death: { frames: 4 }, block: { frames: 4 } },
  "black-knight-c": { idle: { frames: 6 }, walk: { frames: 8 }, attack01: { frames: 8 }, attack02: { frames: 9 }, attack03: { frames: 13 }, hurt: { frames: 4 }, death: { frames: 10 } },
  "blood-monster-a": { idle: { frames: 6 }, walk: { frames: 8 }, attack01: { frames: 8 }, attack02: { frames: 8 }, hurt: { frames: 4 }, death: { frames: 4 } },
  "blood-monster-b": { idle: { frames: 6 }, attack01: { frames: 8 }, attack02: { frames: 9 }, hurt: { frames: 4 }, death: { frames: 6 } },
  "demon-a": { idle: { frames: 6 }, walk: { frames: 8 }, attack01: { frames: 7 }, attack02: { frames: 7 }, hurt: { frames: 4 }, death: { frames: 4 } },
  "demon-b": { idle: { frames: 6 }, walk: { frames: 8 }, attack01: { frames: 9 }, attack02: { frames: 6 }, hurt: { frames: 4 }, death: { frames: 4 } },
  "demon-c": { idle: { frames: 6 }, walk: { frames: 6 }, attack01: { frames: 6 }, attack02: { frames: 6 }, hurt: { frames: 4 }, death: { frames: 4 } },
  "demon-d": { idle: { frames: 6 }, walk: { frames: 8 }, attack01: { frames: 11 }, attack02: { frames: 18 }, attack03: { frames: 12 }, hurt: { frames: 4 }, death: { frames: 4 } },
  "demon-e": { idle: { frames: 6 }, walk: { frames: 8 }, attack01: { frames: 8 }, attack02: { frames: 13 }, attack03: { frames: 8 }, hurt: { frames: 4 }, death: { frames: 4 } },
  "demoness-a": { idle: { frames: 6 }, walk: { frames: 8 }, attack01: { frames: 9 }, attack02: { frames: 15 }, attack03: { frames: 16 }, hurt: { frames: 4 }, death: { frames: 4 } },
  "demoness-b": { idle: { frames: 6 }, walk: { frames: 6 }, attack01: { frames: 8 }, attack02: { frames: 8 }, hurt: { frames: 4 }, death: { frames: 4 } },
  "elite-orc": { idle: { frames: 6 }, walk: { frames: 8 }, attack01: { frames: 7 }, attack02: { frames: 11 }, attack03: { frames: 9 }, hurt: { frames: 4 }, death: { frames: 4 } },
  "eyeball-monster": { idle: { frames: 6 }, walk: { frames: 6 }, attack01: { frames: 8 }, attack02: { frames: 8 }, attack03: { frames: 6 }, hurt: { frames: 4 }, death: { frames: 4 } },
  "flame-golem": { idle: { frames: 6 }, walk: { frames: 12 }, attack01: { frames: 9 }, attack02: { frames: 9 }, attack03: { frames: 9 }, hurt: { frames: 4 }, death: { frames: 6 } },
  "ghostfire": { idle: { frames: 6 }, attack01: { frames: 6 }, attack02: { frames: 7 }, hurt: { frames: 4 }, death: { frames: 6 } },
  "greatsword-skeleton": { idle: { frames: 6 }, walk: { frames: 9 }, attack01: { frames: 9 }, attack02: { frames: 12 }, attack03: { frames: 8 }, hurt: { frames: 4 }, death: { frames: 4 } },
  "hellbat": { idle: { frames: 6 }, attack01: { frames: 6 }, attack02: { frames: 7 }, hurt: { frames: 4 }, death: { frames: 4 } },
  "hellhound": { idle: { frames: 6 }, walk: { frames: 8 }, attack01: { frames: 8 }, attack02: { frames: 8 }, hurt: { frames: 4 }, death: { frames: 4 } },
  "knight": { idle: { frames: 6 }, walk: { frames: 8 }, attack01: { frames: 7 }, attack02: { frames: 10 }, attack03: { frames: 11 }, hurt: { frames: 4 }, death: { frames: 4 }, block: { frames: 4 } },
  "knight-templar": { idle: { frames: 6 }, walk: { frames: 8 }, attack01: { frames: 7 }, attack02: { frames: 8 }, attack03: { frames: 11 }, hurt: { frames: 4 }, death: { frames: 4 }, block: { frames: 4 } },
  "lancer": { idle: { frames: 6 }, walk: { frames: 8 }, attack01: { frames: 6 }, attack02: { frames: 9 }, attack03: { frames: 8 }, hurt: { frames: 4 }, death: { frames: 4 } },
  "lava-slime": { idle: { frames: 6 }, walk: { frames: 6 }, attack01: { frames: 6 }, attack02: { frames: 9 }, hurt: { frames: 4 }, death: { frames: 4 } },
  "minotaur": { idle: { frames: 6 }, walk: { frames: 8 }, attack01: { frames: 8 }, attack02: { frames: 7 }, attack03: { frames: 7 }, hurt: { frames: 4 }, death: { frames: 4 } },
  "necromancer": { idle: { frames: 6 }, walk: { frames: 6 }, attack01: { frames: 9 }, attack02: { frames: 10 }, hurt: { frames: 4 }, death: { frames: 9 } },
  "orc": { idle: { frames: 6 }, walk: { frames: 8 }, attack01: { frames: 6 }, attack02: { frames: 6 }, hurt: { frames: 4 }, death: { frames: 4 } },
  "orc-rider": { idle: { frames: 6 }, walk: { frames: 8 }, attack01: { frames: 8 }, attack02: { frames: 9 }, attack03: { frames: 11 }, hurt: { frames: 4 }, death: { frames: 4 }, block: { frames: 4 } },
  "priest": { idle: { frames: 6 }, walk: { frames: 8 }, attack01: { frames: 9 }, hurt: { frames: 4 }, death: { frames: 4 } },
  "skeleton": { idle: { frames: 6 }, walk: { frames: 8 }, attack01: { frames: 6 }, attack02: { frames: 7 }, hurt: { frames: 4 }, death: { frames: 4 }, block: { frames: 4 } },
  "skeleton-archer": { idle: { frames: 6 }, walk: { frames: 8 }, attack01: { frames: 9 }, hurt: { frames: 4 }, death: { frames: 4 } },
  "slime": { idle: { frames: 6 }, walk: { frames: 6 }, attack01: { frames: 6 }, attack02: { frames: 12 }, hurt: { frames: 4 }, death: { frames: 4 } },
  "soldier": { idle: { frames: 6 }, walk: { frames: 8 }, attack01: { frames: 6 }, attack02: { frames: 6 }, attack03: { frames: 9 }, hurt: { frames: 4 }, death: { frames: 4 } },
  "swordsman": { idle: { frames: 6 }, walk: { frames: 8 }, attack01: { frames: 7 }, attack02: { frames: 15 }, attack03: { frames: 12 }, hurt: { frames: 5 }, death: { frames: 4 } },
  "warlock": { idle: { frames: 6 }, walk: { frames: 8 }, attack01: { frames: 7 }, attack02: { frames: 6 }, hurt: { frames: 4 }, death: { frames: 11 } },
  "werebear": { idle: { frames: 6 }, walk: { frames: 8 }, attack01: { frames: 9 }, attack02: { frames: 13 }, attack03: { frames: 9 }, hurt: { frames: 4 }, death: { frames: 4 } },
  "werewolf": { idle: { frames: 6 }, walk: { frames: 8 }, attack01: { frames: 9 }, attack02: { frames: 13 }, hurt: { frames: 4 }, death: { frames: 4 } },
  "wizard": { idle: { frames: 6 }, walk: { frames: 8 }, attack01: { frames: 6 }, attack02: { frames: 9 }, hurt: { frames: 4 }, death: { frames: 4 } },
};

// Display names, for any future character-select UI.
// A character's attacks from lightest to heaviest, filtered to the ones it
// actually ships. Nine of the roster have all three, the Priest has one, most
// have two.
//
// Resolving against the real metadata is the whole point: FighterSprite falls
// back to `idle` for a pose a character doesn't have, so naming "attack02" and
// hoping meant the Priest played no attack at all — the swing just vanished.
export function attackChain(slug: string): SpriteState[] {
  const meta = SPRITES[slug];
  const chain: SpriteState[] = [];
  for (const s of ["attack01", "attack02", "attack03"] as const) {
    if (meta?.[s]) chain.push(s);
  }
  return chain.length > 0 ? chain : ["attack01"];
}

/** Heaviest clip a character has. Highest tier of {@link attackPose}. */
export const MAX_ATTACK_TIER = 2;

// Escalation, clamped: tier 2 on a character with two attacks plays its
// second, not nothing. So a fighter with a short chain simply tops out
// earlier rather than losing its swing at high tiers.
export function attackPose(slug: string, tier: number): SpriteState {
  const chain = attackChain(slug);
  return chain[Math.min(Math.max(tier, 0), chain.length - 1)];
}

/** The pose for a critical hit: always the heaviest thing on the sheet. */
export function critPose(slug: string): SpriteState {
  return attackPose(slug, MAX_ATTACK_TIER);
}

// How far each character has to move to sit in the middle of its own box.
//
// The source frames are 100x100, but nobody is drawn in the centre of one: the
// frame is sized for the character's widest animation, so a standing figure
// ends up wherever that pose leaves it. Measured across the roster, an idle
// character's content centre lands anywhere from 6px left of the frame centre
// to 6px right, and up to 10px below it — which is why the hero chips looked
// like the sprites had been dropped in at random.
//
// Each offset is the correction in FRAME pixels, computed from the union of
// every frame of that character's `idle` clip:  (50 - centre).
//
// Deliberately measured from idle alone and then applied to every pose. Per
// pose it would be "correct" and look wrong: an attack's content centre sits
// forward of the body, so re-centring per pose would slide the character
// backwards each time it swung. Planting it by its resting pose is what lets
// the sword extend from a fighter who stays put.
export const SPRITE_OFFSET: Record<string, { x: number; y: number }> = {
  "archer": { x: -1, y: 0 },
  "armored-axeman": { x: -3, y: 2 },
  "armored-orc": { x: -4, y: 2 },
  "armored-skeleton": { x: -4, y: 3 },
  "bat": { x: 0, y: 2 },
  "black-knight-a": { x: -2, y: 6 },
  "black-knight-b": { x: 0, y: 2 },
  "black-knight-c": { x: -6, y: 6 },
  "blood-monster-a": { x: -2, y: -1 },
  "blood-monster-b": { x: -3, y: 3 },
  "demon-a": { x: -3, y: 1 },
  "demon-b": { x: -2, y: 0 },
  "demon-c": { x: -4, y: 4 },
  "demon-d": { x: -6, y: 4 },
  "demon-e": { x: -5, y: 2 },
  "demoness-a": { x: -5, y: 4 },
  "demoness-b": { x: 1, y: 3 },
  "elite-orc": { x: -6, y: 4 },
  "eyeball-monster": { x: 0, y: -2 },
  "flame-golem": { x: -2, y: 6 },
  "ghostfire": { x: -2, y: 7 },
  "greatsword-skeleton": { x: 6, y: 2 },
  "hellbat": { x: 1, y: 4 },
  "hellhound": { x: 0, y: 0 },
  "knight": { x: -4, y: 1 },
  "knight-templar": { x: -6, y: 0 },
  "lancer": { x: 0, y: 10 },
  "lava-slime": { x: 2, y: -1 },
  "minotaur": { x: -6, y: 1 },
  "necromancer": { x: 4, y: 5 },
  "orc": { x: -4, y: 0 },
  "orc-rider": { x: -3, y: 6 },
  "priest": { x: -2, y: 2 },
  "skeleton": { x: -6, y: 0 },
  "skeleton-archer": { x: -2, y: 2 },
  "slime": { x: 2, y: 0 },
  "soldier": { x: 0, y: 1 },
  "swordsman": { x: -4, y: 1 },
  "warlock": { x: 0, y: 4 },
  "werebear": { x: -2, y: 0 },
  "werewolf": { x: -6, y: 0 },
  "wizard": { x: -2, y: 1 },
};

export const CHARACTER_NAMES: Record<string, string> = {
  "archer": "Archer",
  "armored-axeman": "Armored Axeman",
  "armored-orc": "Armored Orc",
  "armored-skeleton": "Armored Skeleton",
  "bat": "Bat",
  "black-knight-a": "Black Knight A",
  "black-knight-b": "Black Knight B",
  "black-knight-c": "Black Knight C",
  "blood-monster-a": "Blood Monster_A",
  "blood-monster-b": "Blood Monster_B",
  "demon-a": "Demon_A",
  "demon-b": "Demon_B",
  "demon-c": "Demon_C",
  "demon-d": "Demon_D",
  "demon-e": "Demon_E",
  "demoness-a": "Demoness_A",
  "demoness-b": "Demoness_B",
  "elite-orc": "Elite Orc",
  "eyeball-monster": "Eyeball Monster",
  "flame-golem": "Flame Golem",
  "ghostfire": "Ghostfire",
  "greatsword-skeleton": "Greatsword Skeleton",
  "hellbat": "Hellbat",
  "hellhound": "Hellhound",
  "knight": "Knight",
  "knight-templar": "Knight Templar",
  "lancer": "Lancer",
  "lava-slime": "Lava Slime",
  "minotaur": "Minotaur",
  "necromancer": "Necromancer",
  "orc": "Orc",
  "orc-rider": "Orc rider",
  "priest": "Priest",
  "skeleton": "Skeleton",
  "skeleton-archer": "Skeleton Archer",
  "slime": "Slime",
  "soldier": "Soldier",
  "swordsman": "Swordsman",
  "warlock": "Warlock",
  "werebear": "Werebear",
  "werewolf": "Werewolf",
  "wizard": "Wizard",
};

